#!/bin/sh
#
# /etc/rc.d/php-fpm: start/stop FastCGI Process Manager
#

case $1 in
start)
	/usr/sbin/php-fpm
	;;
stop)
	killall -q /usr/sbin/php-fpm
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
*)
	echo "usage: $0 [start|stop|restart]"
	;;
esac

# End of file
